name: 'OZI Provenance'
description: 'Generate provenance attestations for OZI build artifacts'
author: 'OZI Project'
branding:
  color: 'blue'
  icon: 'lock'
inputs:
  release-tag:
    description: release tag to upload provenance to
    required: true
runs:
  using: composite
  steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      with:
        fetch-depth: 0
    - uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53
    - id: attest
      uses: actions/attest-build-provenance@a2bbfa25375fe432b6a289bc6b6cd05ecd0c4c32 # 4.1.0
      with:
        subject-path: 'artifact/dist/*'
    - run: gh release upload "$RELEASE_TAG" "$BUNDLE_PATH"
      env:
        BUNDLE_PATH: ${{ steps.attest.outputs.bundle-path }}
        RELEASE_TAG: ${{ inputs.release-tag }}
        GITHUB_TOKEN: ${{ github.token }}
      shell: bash
