name: 'OZI Provenance'
description: 'Generate provenance attestations for OZI build artifacts'
author: 'OZI Project'
branding:
  color: 'blue'
  icon: 'lock'
inputs:
  release-tag:
    description: release tag to upload provenance to
    required: true
runs:
  using: composite
  steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      with:
        fetch-depth: 0
    - uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0
    - id: attest
      uses: actions/attest-build-provenance@977bb373ede98d70efdf65b84cb5f73e068dcc2a # 3.0.0
      with:
        subject-path: 'artifact/dist/*'
    - run: gh release upload "$RELEASE_TAG" "$BUNDLE_PATH"
      env:
        BUNDLE_PATH: ${{ steps.attest.outputs.bundle-path }}
        RELEASE_TAG: ${{ inputs.release-tag }}
        GITHUB_TOKEN: ${{ github.token }}
      shell: bash
