name: 'OZI Provenance'
description: 'Generate provenance attestations for OZI build artifacts'
author: 'OZI Project'
branding:
  color: 'blue'
  icon: 'lock'
inputs:
  release-tag:
    description: release tag to upload provenance to
    required: true
runs:
  using: composite
  steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      with:
        fetch-depth: 0
    - uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093
    - id: attest
      uses: actions/attest-build-provenance@e8998f949152b193b063cb0ec769d69d929409be # 2.4.0
      with:
        subject-path: 'artifact/dist/*'
    - run: gh release upload "$RELEASE_TAG" "$BUNDLE_PATH"
      env:
        BUNDLE_PATH: ${{ steps.attest.outputs.bundle-path }}
        RELEASE_TAG: ${{ inputs.release-tag }}
        GITHUB_TOKEN: ${{ github.token }}
      shell: bash
